### ISSUE TITLE
BUG: stopwords_pt filter não funciona se usado após asciifolding

### ISSUE THREAD

**Issue by flaviomartins** [diogoalmiro/ecli-indexer#1]
A solução mais simples parece-me colocar o asciifolding filter mais para o final

https://github.com/diogoalmiro/ecli-indexer/blob/28cd57a26ab2eed262ab7486c97ff941878e67cd/jurisprudencia.js#L145

**Comment by diogoalmiro** [comment]
9adee5deda93ae235ac961443cd4210cb5ad2b0c fixes this.
