### ISSUE TITLE
ENH: Externalize stopword list file

### ISSUE THREAD

**Issue by flaviomartins** [diogoalmiro/ecli-indexer#2]
https://github.com/diogoalmiro/ecli-indexer/blob/28cd57a26ab2eed262ab7486c97ff941878e67cd/jurisprudencia.js#L153

Seria melhor fazer referência a um ficheiro com stopwords (uma por linha como o elasticsearch suporta) ao invés de listar num JsonArray. 

Ref: https://github.com/LIAAD/yake/blob/master/yake/StopwordsList/stopwords_pt.txt

**Comment by diogoalmiro** [comment]
@flaviomartins valeria a pena usar o valor _portuguese_ para as stopwords?
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stop-tokenfilter.html#analysis-stop-tokenfilter-stop-words-by-lang
sendo a lista: https://github.com/apache/lucene/blob/main/lucene/analysis/common/src/resources/org/apache/lucene/analysis/snowball/portuguese_stop.txt

**Comment by diogoalmiro** [comment]
Quanto a usar um ficheiro fico com um pé atrás com a parte de se ter de usar uma path do ficheiro (seja ela relativa ou absoluta). (stopwords_path)
Sendo que este repositório não implica que a instalação esteja na mesma máquina.
