### ISSUE TITLE
BUG: Corrigir o search sem explicit default_field

### ISSUE THREAD

**Issue by flaviomartins** [diogoalmiro/ecli-indexer#3]
https://github.com/diogoalmiro/ecli-indexer/blob/28cd57a26ab2eed262ab7486c97ff941878e67cd/jurisprudencia.js#L110

O Elasticsearch tem por omissão "default_field: text". Seria bom criar um field "text" que agrege por exemplo os fields Sumário e o Texto.

Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/copy-to.html

**Comment by diogoalmiro** [comment]
O default field é "*" https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-query-default-field
Podemos criar um outro field que agrupe todo o conteúdo num único campo.

**Comment by flaviomartins** [comment]
Qual é o status?
